// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9YPG3YQNC-6Y4VkfmwrUUwcch6BmqOxw',
    appId: '1:34933448275:android:0194cf070e93a52888b0a6',
    messagingSenderId: '34933448275',
    projectId: 'sport-news-90485',
    storageBucket: 'sport-news-90485.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaMvI2q0OdiIUyKCloRJgXfuJK2mtYclE',
    appId: '1:34933448275:ios:3881511a57a249a388b0a6',
    messagingSenderId: '34933448275',
    projectId: 'sport-news-90485',
    storageBucket: 'sport-news-90485.appspot.com',
    iosClientId: '34933448275-e5r4ijm1bsg8qboo3he096ta0no246c5.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
